### ISSUE TITLE
Not using the Codec?

### ISSUE THREAD

**Issue by sdrafahl** [flavray/avro-rs#98] opened 2019-10-24 18:06 UTC
So I am trying to write the snappy compressed Avro to a file. I am giving the write from the given example the Snappy codec.

`let mut writer = Writer::with_codec(&schema, Vec::new(), Codec::Snappy);`

When I print what into_inner(); returns I see a vector printed with integers in it. I can only assume that is the avro encoded or something. However when I change the codec to Codec::Null the vector is no different. I am a little confused on how the codec is used and how I can get the compressed avro written to a file?

I should also note that I check the vector and its not valid Snappy.

**Comment by poros** [comment] 2019-10-25 09:47
Just to make sure everything is in order, did you turn the `snappy` feature on in your `Cargo.toml`?

**Comment by sdrafahl** [comment] 2019-10-28 00:39
@poros I did, I ended up just manually compressing it with a different Snappy library on top of the avro encoding. That worked but before my cargo had.

```
[dependencies.avro-rs]
version = "0.6"
features = ["snappy"]
```

**Comment by poros** [comment] 2019-12-31 13:21
@sdrafahl I tried to reproduce what you described above about `Codec:Null` and `Codec:Snappy` giving back the same vector as result of `Writer::into_inner`, but they are different in my experiment:

```rust
#[cfg(feature = "snappy")]
    #[test]
    fn test_writer_with_codec_difference() {
        let schema = Schema::parse_str(SCHEMA).unwrap();

        let mut writer = Writer::with_codec(&schema, Vec::new(), Codec::Null);
        let mut record = Record::new(&schema).unwrap();
        record.put("a", 27i64);
        record.put("b", "foo");
        let n1 = writer.append(record.clone()).unwrap();
        let n2 = writer.append(record.clone()).unwrap();
        let n3 = writer.flush().unwrap();
        let result = writer.into_inner();

        let mut other_writer = Writer::with_codec(&schema, Vec::new(), Codec::Snappy);
        let mut other_record = Record::new(&schema).unwrap();
        other_record.put("a", 27i64);
        other_record.put("b", "foo");
        let other_n1 = other_writer.append(other_record.clone()).unwrap();
        let other_n2 = other_writer.append(other_record.clone()).unwrap();
        let other_n3 = other_writer.flush().unwrap();
        let other_result = other_writer.into_inner();

        println!("null {:?}", result);
        println!("snappy {:?}", other_result);

        assert_ne!(other_result, result);
```

```
test writer::tests::test_writer_with_codec_difference ... ok
null [79, 98, 106, 1, 4, 20, 97, 118, 114, 111, 46, 99, 111, 100, 101, 99, 8, 110, 117, 108, 108, 22, 97, 118, 114, 111, 46, 115, 99, 104, 101, 109, 97, 222, 1, 123, 34, 116, 121, 112, 101, 34, 58, 34, 114, 101, 99, 111, 114, 100, 34, 44, 34, 110, 97, 109, 101, 34, 58, 34, 116, 101, 115, 116, 34, 44, 34, 102, 105, 101, 108, 100, 115, 34, 58, 91, 123, 34, 110, 97, 109, 101, 34, 58, 34, 97, 34, 44, 34, 116, 121, 112, 101, 34, 58, 34, 108, 111, 110, 103, 34, 44, 34, 100, 101, 102, 97, 117, 108, 116, 34, 58, 52, 50, 125, 44, 123, 34, 110, 97, 109, 101, 34, 58, 34, 98, 34, 44, 34, 116, 121, 112, 101, 34, 58, 34, 115, 116, 114, 105, 110, 103, 34, 125, 93, 125, 0, 115, 214, 5, 31, 39, 212, 38, 28, 214, 77, 126, 43, 33, 1, 8, 225, 4, 20, 54, 6, 102, 111, 111, 54, 6, 102, 111, 111, 115, 214, 5, 31, 39, 212, 38, 28, 214, 77, 126, 43, 33, 1, 8, 225]
snappy [79, 98, 106, 1, 4, 20, 97, 118, 114, 111, 46, 99, 111, 100, 101, 99, 12, 115, 110, 97, 112, 112, 121, 22, 97, 118, 114, 111, 46, 115, 99, 104, 101, 109, 97, 222, 1, 123, 34, 116, 121, 112, 101, 34, 58, 34, 114, 101, 99, 111, 114, 100, 34, 44, 34, 110, 97, 109, 101, 34, 58, 34, 116, 101, 115, 116, 34, 44, 34, 102, 105, 101, 108, 100, 115, 34, 58, 91, 123, 34, 110, 97, 109, 101, 34, 58, 34, 97, 34, 44, 34, 116, 121, 112, 101, 34, 58, 34, 108, 111, 110, 103, 34, 44, 34, 100, 101, 102, 97, 117, 108, 116, 34, 58, 52, 50, 125, 44, 123, 34, 110, 97, 109, 101, 34, 58, 34, 98, 34, 44, 34, 116, 121, 112, 101, 34, 58, 34, 115, 116, 114, 105, 110, 103, 34, 125, 93, 125, 0, 43, 86, 32, 150, 161, 129, 104, 9, 168, 37, 54, 125, 177, 8, 146, 36, 4, 32, 10, 36, 54, 6, 102, 111, 111, 54, 6, 102, 111, 111, 31, 157, 101, 245, 43, 86, 32, 150, 161, 129, 104, 9, 168, 37, 54, 125, 177, 8, 146, 36]
```

Is it similar to what you were trying? Can you show me what you did?

In addition, the end result won't be valid snappy because of the avro magic bytes and headers, but the payload should be snappy encoded.

**Comment by poros** [comment] 2020-01-23 20:43
I am going to close the issue for now, as I cannot really reproduce it. But if you still have this problem, please do not hesitate to reach out again.

**Closed by poros** 2020-01-23 20:43 UTC
Labels: bug, question
