### ISSUE TITLE
Failing to decode record type referencing an enum

### ISSUE THREAD

**Issue by ajayrathore** [flavray/avro-rs#117] opened 2020-04-10 08:45 UTC
Seems like avro-rs library cannot parse following message

```
{
  "type": "record",
  "name": "mymsg",
  "namespace": "myns",
  "fields": [
    {
      "name": "myid",
      "type": "int"
    },
    {
      "name": "c1",
      "type": {
        "type": "enum",
        "name": "myflag",
        "symbols": [
          "A",
          "B",
          "C"
        ]
      }
    },
    {
      "name": "c2",
      "type": "myflag"
    }
  ]
}
```

I get following error

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SRCError { error: "Could not parse schema", side: Some("Failed to parse schema: Unknown type: myflag"), retriable: false, cached: true }', src/receiver.rs:84:19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Is this something you can fix?

**Comment by poros** [comment] 2020-04-11 16:20
Yeah, the library has no support for recursive types yet :/
Closing as duplicate of #92

**Closed by poros** 2020-04-11 16:20 UTC
