### ISSUE TITLE
Cannot parse schema with type cross-referencing

### ISSUE THREAD

**Issue by praetp** [flavray/avro-rs#109] opened 2020-02-26 20:43 UTC
```
    let raw_schema = r#"
    {
        "type": "record",
        "name": "test",
        "fields": [
            {"name": "a", 
             "type": {
                "name": "mytype",
                "type": "enum",
                "symbols": [
                       "SYMBOL_ONE"
                ]             
            }},
            {"name": "b", "type": "mytype"}
        ]
    }
    "#;
    let result = Schema::parse_str(raw_schema);
```
This panics with `ParseSchemaError("Unknown type: mytype")`.
When I "inline" the type, it works.

If you want I can write a test for it.
Not sure if this related to https://github.com/flavray/avro-rs/issues/92.

**Comment by poros** [comment] 2020-02-29 13:21
Yes, this one is indeed a duplicate of #92. I am going to close this issue as duplicate in order to keep any future discussion on the same thread.

**Closed by poros** 2020-02-29 13:21 UTC
