### ISSUE TITLE
Auto-generating schemas? 

### ISSUE THREAD

**Issue by bzm3r** [flavray/avro-rs#149] opened 2020-07-19 17:42 UTC
I wondering if I am missing an existing solution to auto-generate schemas from Rust structs?

**Comment by poros** [comment] 2020-07-19 23:11
Hi! The library doesn't have such a feature, neither I know of nay crate that offers it (there is one that does the opposite afaik)

**Comment by bzm3r** [comment] 2020-07-20 03:38
Thanks! I have been working today on a simple (very bare bones, geared towards my use case) proc_macro based schema generator. Once I am done, would you be interested in reviewing it and suggesting improvements?

**Comment by poros** [comment] 2020-07-20 19:59
Perhaps I can give it a look? No promises, though. I don't have much time to dedicate to open source these days and at least I'd like to keep this library in shape.

**Comment by clojurians-org** [comment] 2020-08-01 07:21
the js avro library has already offer this function:
```
https://github.com/mtth/avsc

https://github.com/mtth/avsc/wiki/Advanced-usage#type-inference
```

**Comment by clojurians-org** [comment] 2020-08-12 01:52
it seem this function can be done with two library combation .
the first one generate json schema from serde, the second can convert json schema to avro schema.

https://github.com/GREsau/schemars
https://github.com/mozilla/jsonschema-transpiler

**Comment by 0xcaff** [comment] 2020-09-10 06:53
@poros What's the library which goes the other way (Avro schema to rust structs)?

**Comment by 0xcaff** [comment] 2020-09-10 06:54
I think this is a duplicate of https://github.com/flavray/avro-rs/issues/62

**Comment by poros** [comment] 2020-09-11 11:15
Closing as duplicate of #62

**Closed by poros** 2020-09-11 11:15 UTC
Labels: question
